[outcomes]
labels = ["outcome_SuspectedMI",
    "outcome_PE",
    "outcome_HF",
    "outcome_AD",
    "outcome_myocarditis",
    "outcome_AMI",
    "outcome_CMI"]

display = ["Suspected Acute MI",
    "Diagnosed Pulmonary Embolism",
    "Diagnosed Heart Failure",
    "Diagnosed Aortic Dissection",
    "Diagnosed Myocarditis",
    "Diagnosed Acute Myocardial Injury",
    "Diagnosed Chronic Myocardial Injury"]
colormap = ['#d7191c', '#fdae61', '#abd9e9', '#2c7bb6']

[attributes]
labels = ['gender', 'race_group', 'marital_status', 'insurance']
display = ['Sex', 'Ethnicity', 'Marital Status', 'Insurance']
nonnormal = [
    "Age",
    "# Unique Previous Comorbidities",
    "Temperature (deg-C)",
    "Systolic Blood Pressure (mmHg)",
    "Heart Rate (bpm)",
    "Oxygen Saturation (%)",
    "Respiratory Rate (breaths/min)",
    "Hemoglobin (g/dL)",
    "eGFR (mL/min/1.73msq)",
    "Troponin T (ng/L)",
    "White Blood Cell Count (10^9/L)",
    "Creatinine (micmol/L)",
    "Urea Nitrogen (mmol/L)",
    "Hematocrit (%)",
    "Platelet Count (10^9/L)",
    "Potassium (mmol/L)",
    "Sodium (mmol/L)",
    "Chloride (mmol/L)",
    "Bicarbonate (mmol/L)",
    "Anion Gap (mmol/L)",
    "Creatine Kinase-MB (ng/mL)",
    "C-Reactive Protein (mg/L)"
]
categorical = ["Sex", "Ethnicity", "Marital Status", "Insurance", "Mode of ED Arrival",
    "ECG Normal",
    "ECG ST Elevation",
    "ECG Myocardial Ischemia",
    "Suggestive Symptoms",
    "Chest Pain",
    "Breathlessness",
    "Heart Palpitations",
    "Ischaemic Heart Disease",
    "Hypertension",
    "Stroke",
    "Peripheral Arterial Disease",
    "Old Myocardial Infarction",
    "Cerebrovascular Disease",
    "Diabetes",
    "Chronic Kidney Disease",
    "Arthritis",
    "Hip Fracture",
    "Progressive Neurological Disease",
    "Chronic Obstructive Pulmonary Disease",
    "Pulmonary Fibrosis",
    "Asthma",
    "Bronchiectasis",
    "Epilepsy",
    "Obesity",
    "Atrial Fibrillation",
    "Alcohol/Substance Misuse",
    "Psychiatric Disorders",
    "Depression",
    "Percutaneous Coronary Intervention",
    "Coronary Angiography",
    "Previous Revascularization"]

vitals = ['Diastolic blood pressure', 'Heart rate', 'Oxygen saturation', 'Respiratory rate', 'Systolic blood pressure', 'Temperature']
dbindices = [86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

[age]
bins = [18, 49, 59, 69, 79, 91]
labels = ['<50', '50-59', '60-69', '70-79', '80+']

[timeseries]
vitals_freq = '30m'
lab_freq = '5h'

[paths]
model_paths = ["ext_stay_7_concat_static_timeseries_notes", "ext_stay_7_concat_static_timeseries_notes_db", "ext_stay_7_concat_static_timeseries_notes_db2", "ext_stay_7_concat_static_timeseries_notes_db3", "ext_stay_7_concat_static_timeseries_notes_db4", "ext_stay_7_concat_static_timeseries_notes_db5"]
model_names = ["ES: IF-EHR+TS+NT", "Debiased: ld=0.2", "Debiased: ld=0.5", "Debiased: ld=1", "Debiased: ld=2", "Debiased: ld=5"]
model_colors = ["#abd9e9", "#4575b4", "#fee090", "#fdae61", "#d73027", "#fc1fd0"]

[shap_profile]
sex = 'F'
ethnicity = 'White'
marital_status = 'Married'
insurance = 'Medicare'
